replicaCount: 2

autoscaling:
  enabled: true
  replicas:
    min: 2
    max: 10
  avgCpuUtilization: 70
  behavior:
    stabilizationWindowSeconds:
      scaleUp: 0
      scaleDown: 120

resources:
  requests:
    cpu: 30m
    memory: 128Mi

image:
  # Set "repository" name of your image for manual Helm install and upgrade.
  repository: browserless/chrome
  tag: latest
  pullPolicy: Always
  serviceAccount: pdfgeneratorsa

service:
  name: pdfgenerator
  type: ClusterIP
  externalPort: 80
  # If your application is running on another port, change only the internal port.
  internalPort: 3000

ingressRoute:
  name: pdf-generator-ingress-route
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`ttd.apps.at22.altinn.cloud`)&&PathPrefix(`/pdf`)
      kind: Rule
      services:
        - name: pdfgenerator-pdf-generator
          port: 80
      middlewares:
        - name: hsts-header
  tls:
    options:
      name: tls-options
    secretName: ssl-cert
